[phases.setup]
nixPkgs = [
  'nodejs_20',
  'chromium',
  'nss',
  'freetype',
  'harfbuzz',
  'ca-certificates',
  'ttf-freefont',
  'xorg.libxscrnsaver',
  'xorg.libX11',
  'xorg.libXcomposite',
  'xorg.libXcursor',
  'xorg.libXdamage',
  'xorg.libXext',
  'xorg.libXfixes',
  'xorg.libXi',
  'xorg.libXrender',
  'xorg.libXtst',
  'libxshmfence',
  'xdg-utils',
  'libdrm',
  'mesa',
  'gtk3'
]

[phases.install]
cmds = [
  'npm ci --prefer-offline --no-audit',
  'echo "Verificando Chromium..." && which chromium && chromium --version || echo "Chromium no encontrado"'
]

[start]
cmd = '''
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
export CHROME_BIN=/usr/bin/chromium
export CHROMIUM_PATH=/usr/bin/chromium
export DISPLAY=:99

# Start virtual framebuffer
Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

# Debug info
echo "🔧 Debug: Environment Setup"
echo "PUPPETEER_EXECUTABLE_PATH=$PUPPETEER_EXECUTABLE_PATH"
echo "CHROME_BIN=$CHROME_BIN"
echo "CHROMIUM_PATH=$CHROMIUM_PATH"

# Start bot with better error handling
node index.js
'''

[variables]
PUPPETEER_SKIP_DOWNLOAD = 'true'
CHROME_BIN = '/usr/bin/chromium'