[phases.setup]
nixPkgs = ['nodejs_20', 'chromium']

[phases.install]
cmds = ['npm ci --prefer-offline --no-audit']

[start]
cmd = "node index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium'