[phases.setup]
nixPkgs = [
  'nodejs_20',
  'chromium',
  'nss',
  'freetype',
  'harfbuzz',
  'cacert',
  'ttf-freefont',
  'xorg.libxscrnsaver',
  'xorg.libX11',
  'xorg.libXcomposite',
  'xorg.libXcursor',
  'xorg.libXdamage',
  'xorg.libXext',
  'xorg.libXfixes',
  'xorg.libXi',
  'xorg.libXrender',
  'xorg.libXtst',
  'libxshmfence',
  'xdg-utils',
  'libdrm',
  'mesa',
  'gtk3'
]

[phases.install]
cmds = [
  'npm ci --prefer-offline --no-audit'
]

[start]
cmd = "node index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium'