[phases.setup]
aptPkgs = [
  "libnss3",
  "libnss3-dev",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgtk-3-0",
  "libgdk-pixbuf2.0-0",
  "libgbm-dev",
  "libasound2t64",
  "libxshmfence-dev", # Might be libxshmfence1 depending on distro version
  "libglu1-mesa",
  "libxrandr2",
  "libxfixes3",
  "libxcomposite1",
  "libxdamage1",
  "libxkbcommon0",
  "libgobject-2.0-0",
  "libdrm2",
  "libx11-xcb1",
  "libpangocairo-1.0-0",
  "libcairo2",
  "chromium", # Keep this one
  "chromium-driver", # Add this
  "chromium-sandbox" # Add this
]