[phases.setup]
nixPkgs = ['nodejs_20', 'chromium', 'nss', 'freetype', 'harfbuzz', 'ca-certificates', 'ttf-freefont']

[phases.install]
cmds = [
  'npm ci --prefer-offline --no-audit --registry=https://registry.npmjs.org/',
  # Verificar instalación de Chromium
  'echo "Verificando Chromium..." && which chromium && chromium --version || echo "Chromium no encontrado"'
]

[start]
# 🔥 CORRECCIÓN CRÍTICA: Paths alternativos para Chromium en Nixpacks/Railway
cmd = '''
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=$(which chromium || echo "/nix/store/$(ls /nix/store | grep chromium | head -n1)/bin/chromium")
export DISPLAY=:99

# Configuración adicional para entorno headless
export CHROME_BIN=$PUPPETEER_EXECUTABLE_PATH
export CHROMIUM_PATH=$PUPPETEER_EXECUTABLE_PATH

echo "🔧 Chromium path: $PUPPETEER_EXECUTABLE_PATH"

# Iniciar bot con reintentos
node index.js
'''

[variables]
PUPPETEER_SKIP_DOWNLOAD = 'true'