[phases.setup]
nixPkgs = [
  'nodejs_20',
  'chromium',
  'nss',
  'freetype',
  'harfbuzz',
  'ca-certificates',
  'ttf-freefont',
  'xorg.libxscrnsaver',
  'xorg.libX11',
  'xorg.libXcomposite',
  'xorg.libXcursor',
  'xorg.libXdamage',
  'xorg.libXext',
  'xorg.libXfixes',
  'xorg.libXi',
  'xorg.libXrender',
  'xorg.libXtst',
  'libxshmfence',
  'xdg-utils',
  'libdrm',
  'mesa',
  'gtk3'
]

[phases.install]
cmds = [
  'npm ci --prefer-offline --no-audit',
  'echo "✅ Verificando Chromium..." && which chromium && chromium --version || echo "❌ Chromium no encontrado"'
]

[start]
cmd = '''
# Set Chromium path for puppeteer helper
export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Debug info
echo "🔧 Chromium Configuration:"
echo "  PUPPETEER_EXECUTABLE_PATH=$PUPPETEER_EXECUTABLE_PATH"
which chromium || echo "⚠️ Chromium not in PATH"

# Start the bot
node index.js
'''

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'