# nixpacks.toml
[phases.setup]
aptPkgs = [
"chromium", "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libgbm1", "libasound2",
"libpangocairo-1.0-0", "libxss1", "libgtk-3-0", "libxshmfence1", "libglu1", "fonts-liberation", "libu2f-udev"
]


[phases.install]
cmds = ["npm install --omit=dev --no-audit"]


[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NODE_ENV = "production"